db_user: "postgres"
db_password: "123"
db_name: "monoboi"
db_host: "localhost"
db_port: "5432"
cors_origins: "*"
jwt_secret: "secret"
cep_aberto_api_token: "123"
own_public_url: "'http://localhost:8089'"
oauth_google_key: "123"
oauth_google_secret: "123"
oauth_google_callback_url: "http://localhost:8089/api/auth/flow/google/callback"
oauth_session_secret: "secret"
oauth_redirect_url: "https://localhost:4430/auth/login"
